<?php
    session_start();
    if(isset($_SESSION["nom"])){
        unset($_SESSION["nom"]);
        session_destroy();
    }
    if(isset($_SESSION["role"])){
        unset($_SESSION["role"]);
        session_destroy();
    }
    if(isset($_SESSION["table"])){
        unset($_SESSION["table"]);
        session_destroy();
    }
    if(isset($_SESSION["matieres"])){
        unset($_SESSION["matieres"]);
        session_destroy();
    }
    if(isset($_SESSION["moyecart"])){
        unset($_SESSION["moyecart"]);
        session_destroy();
    }
    if(isset($_SESSION["erreur"])){
        unset($_SESSION["erreur"]);
        session_destroy();
    }
    header('location: index.php');
?>